snippet     dockerfile
abbr        ひな形
	#FROM ubuntu:14.04
	FROM debian:jessie
	MAINTAINER yaasita
	#apt
	ADD 02proxy /etc/apt/apt.conf.d/02proxy
	RUN apt-get update
	#package
	RUN apt-get install -y vim git aptitude build-essential
	#ssh
	RUN apt-get install -y openssh-server
	RUN mkdir /var/run/sshd/
	RUN mkdir /root/.ssh
	ADD authorized_keys /root/.ssh/authorized_keys
	RUN echo root:root | chpasswd
	CMD /usr/sbin/sshd -D

